name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"
      - name: Install dependencies
        run: go get .
      - name: Test
        run: go test
      - name: Build
        run: |
          GOOS=darwin GOARCH=arm64 go build -o dist/dkb-report-macos-arm64 dkb-report.go
          GOOS=linux GOARCH=amd64 go build -o dist/dkb-report-linux-amd64 dkb-report.go
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist
